### ISSUE TITLE
Drop down arrow of TSpTBXSubmenuItem button drawn centered

### ISSUE THREAD

**Issue by MShark67** [SilverpointDev/sptbxlib#84]
When a TSpTBXSubmenuItem is a button on a toolbar it appears to be drawing its dropdown arrow centered on the button instead of the area to the right of the icon usually reserved for it.  It looks like this code changed recently and the path doesn't handle a button with no caption and a dropdown.  My fix is to remove the "if TextInfo.IsCaptionShonw then" check, as it appears that it's handled correctly with the SpecialDropDown variable (but I didn't test all options.)

```
        if not IsSpecialDropDown then begin
          // If the caption is shown calculate the right margin, if the caption
          // is not visible center the arrow
          // if TextInfo.IsCaptionShown then   // Fix is to remove this line.
            if View.Orientation <> tbvoVertical then
              ItemInfo.ComboRect := Rect(R.Right - Self.tbDropdownArrowWidth - Self.tbDropdownArrowMargin, 0,
                R.Right - Self.tbDropdownArrowMargin, R.Bottom)
            else
              ItemInfo.ComboRect := Rect(0, R.Bottom - Self.tbDropdownArrowWidth - Self.tbDropdownArrowMargin,
                R.Right, R.Bottom - Self.tbDropdownArrowMargin);
        end

```

**Comment by SilverpointDev** [comment]
Fixed

**Comment by pyscripter** [comment]
@SilverpointDev It appears you forgot to commit the changes.

**Comment by SilverpointDev** [comment]
I forgot to push the changes. Fixed now.
