### ISSUE TITLE
Incorrect TSpTBXRightAlignSpacerItem  behavior in SpTBXTabs under high DPI

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#88]
In commit 7df7fc6eeb9966dd57731142fb75a2943d2bb1b7 CustomWidth was changed from unscaled to scaled.  This change was not reflected in SpTBXTabs.  

You can see the problem if you add a TSpTBXRightAlignSpacerItem  in a TabControl and run in a high DPI monitor.

Solution:

There are two places in which CustomWidth is unscaled in SpTBXTabs  (lines 1627 and 1762).  Remove the call to PPIUnscale.

**Comment by SilverpointDev** [comment]
Fixed

**Comment by pyscripter** [comment]
I cannot see any commits fixing this or the other closed bugs.  Maybe you forgot to push the changes.
